# Generated by Django 5.0 on 2026-02-02 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The category or type of the client (e.g., Retail, Wholesale).', max_length=100, unique=True, verbose_name='Client Type Name')),
            ],
            options={
                'verbose_name': 'Client Type',
                'verbose_name_plural': 'Client Types',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Route Name')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, verbose_name='Day of Week')),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Deliverer')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier for the client.', max_length=20, unique=True, verbose_name='Client Code')),
                ('name', models.CharField(max_length=150, verbose_name='Business Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True, verbose_name='Neighborhood')),
                ('municipality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipality')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector')),
                ('market', models.CharField(blank=True, max_length=100, null=True, verbose_name='Market')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='visits.clienttype', verbose_name='Type')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='visits.route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(verbose_name='Visited At')),
                ('latitude_recorded', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_recorded', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_productive', models.BooleanField(default=False, verbose_name='Is Productive')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Is Valid')),
                ('distance_from_client', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='visits.client', verbose_name='Client')),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Deliverer')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['-visited_at'],
            },
        ),
    ]
