# Generated by Django 5.0 on 2026-02-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Abbreviation'),
        ),
    ]
