# Generated by Django 5.0 on 2026-02-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_clienttype_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='visit',
            name='distance_from_client',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='latitude_recorded',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='visit',
            name='longitude_recorded',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
