# Generated by Django 5.0 on 2026-02-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_alter_client_latitude_alter_client_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='distance_from_client',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
