# Generated by Django 5.0 on 2026-02-21 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_alter_visit_distance_from_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='visits.clienttype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
